Gage metadata additions.
internetofwater/ref_gages pull request #39
Opened 2024-10-04 02:47 UTC by dblodgett-usgs

This PR adds additional metadata to gages to better characterize how well accurate the gage links might be. See #26 and #38 for more.

2024-10-04 18:21 UTC, jds485 requested changes
This looks good. I have not run this code (let me know if you want me to do that). I have some questions for you and a few code suggestions.

2024-10-04 18:21 UTC, jds485 commented on R/gage_locations.R
> +  missing_offset$nhdpv2_link_source[is.na(missing_offset$nhdpv2_offset_m)] <- NA
could do this in 1 line:
```suggestion
  missing_offset[is.na(missing_offset$nhdpv2_offset_m), c('nhdpv2_REACHCODE', 'nhdpv2_REACH_measure','nhdpv2_COMID','nhdpv2_totdasqkm','nhdpv2_link_source')] <- NA
```

2024-10-04 18:21 UTC, jds485 commented on _targets.R
>  nwis_hydrolocation <- "data/nwis_hydrolocations.csv"
Do you want `targets` to track changes to these files? If so, you'll need to create `file` or `file_fast` targets for them. It looks like some of these are tracked.

2024-10-04 18:21 UTC, jds485 commented on _targets.R
>    tar_target("nhdpv2_gage", select(read_sf(nat_db, "Gage"),
general comment: the target name does not need quotes. I actually didn't know you could use quotes!

2024-10-04 18:21 UTC, jds485 commented on reg/ref_gages.csv
How are these two files generated?

2024-10-04 18:21 UTC, jds485 commented on R/gage_locations.R
>    all_gages$nhdpv2_REACHCODE[update_index] <- linked_gages$REACHCODE
If the order is the same, you should be able to do these replacements in 1 line (see example for a different dataset in a comment below)

2024-10-04 18:21 UTC, jds485 commented on R/gage_locations.R
> +                                                  search_radius =  units::set_units(1000, "meters"),
1 km is far to search. Is this based on known location precision issues?

2024-10-04 18:25 UTC, dblodgett-usgs commented on R/gage_locations.R
> +           nhdpv2_COMID = as.numeric(nhdpv2_COMID),
No -- they are strictly integers. I use characters too but comid can be either one.

2024-10-04 18:27 UTC, dblodgett-usgs commented on R/gage_locations.R
> +  nh <- mutate(nh, nhdpv2_link_source = "https://github.com/internetofwater/ref_gages/blob/main/data/nwis_hydrolocations.csv")
These are corrections on publications that aren't really subject to change. The hope is that the file in this repo becomes the place to track manual fixes if another source of truth doesn't become available.

2024-10-04 18:30 UTC, dblodgett-usgs commented on R/gage_locations.R
> +                           # is tens of catchments and within 10%
I actually meant catchments here -- Since things are discretized to catchments for drainage area accumulation, the quanta is one catchment. The comment could read "is tens of catchments (~20-40sqkm) and within 10% drainage area match" since catchments are mostly in the range of 1-4sqkm. Does that make sense?

2024-10-04 18:35 UTC, dblodgett-usgs commented on R/gage_locations.R
> +  bad_da <- all_gages[!is.na(all_gages$da_diff) & # has an estimate
It was actually difference greater than 50% were removed and recalculated. Either way, I did look at what the 50% threshold looked like vs the new scheme. 

The lines here are the threshold: 

![image](https://github.com/user-attachments/assets/437d68a2-d36e-4555-a47d-cff0cdd0f733)
![image](https://github.com/user-attachments/assets/6e0c4de1-1faf-44f9-8463-843dd08487cb)

This is the final filter I came up with

![372610036-ab5d0016-1847-493e-be61-59f19f12edf2](https://github.com/user-attachments/assets/887173aa-acc5-4825-9d10-aa371b5bf774)
![372610162-00633aa9-a544-4e4f-b7ef-077b347fb183](https://github.com/user-attachments/assets/6ca93449-c03b-4457-9d79-68efb415ae15)

2024-10-04 18:38 UTC, dblodgett-usgs commented on _targets.R
>    tar_target("nhdpv2_gage", select(read_sf(nat_db, "Gage"),
hahah -- I didn't know you didn't have to!

2024-10-04 18:39 UTC, dblodgett-usgs commented on R/gage_locations.R
> +                                                  search_radius =  units::set_units(1000, "meters"),
It is far! It has to be this big because of large waterbodies that have artificial paths in the middle but the gage location on the shore. There's actually one in NHDPlusV2 gages that is >50km! on a Lake in upstate new york.

2024-10-04 19:30 UTC, jds485 commented on R/gage_locations.R
> +                           # is tens of catchments and within 10%
This cutoff is for the drainage area, not catchments, right? Do you know that all the gages that meet this criterion have multiple catchments? That's why I was confused by the comment

2024-10-04 20:29 UTC, dblodgett-usgs commented on R/gage_locations.R
> +                           # is tens of catchments and within 10%
I don't -- I'm just going on the knowledge of the typical size of a catchment. Do you think it would be worth investigating gages on the margins? When dealing with such large numbers of features, I tend to plow ahead and try not to get too stuck on details but may be going to far with that approach in this case.

2024-10-07 12:40 UTC, dblodgett-usgs commented on R/gage_locations.R
> +                           # is tens of catchments and within 10%
Since a gage area is estimated to the gage and the nhdplusv2 area is estimated to a catchment outlet, as you get more catchments, the error from a gage being in the middle of a catchment becomes less significant.

2024-10-07 14:52 UTC, jds485 commented on R/gage_locations.R
> +                           # is tens of catchments and within 10%
> Do you think it would be worth investigating gages on the margins?

Probably not for this many gages, as you noted. Do you have a histogram, boxplot, etc. of the catchment drainage areas? I'm wondering how large the catchments can be

2024-10-08 16:48 UTC, dblodgett-usgs commented on R/gage_locations.R
> +                           # is tens of catchments and within 10%
Looking at drainage area for the comids that gages are in...

![image](https://github.com/user-attachments/assets/b58b1cb6-0888-4933-8262-25d7ec5401ba)

```r
> sum(all_area < 20)
[1] 101625
> sum(all_area > 20)
[1] 6125
```

If I only look at gages that have drainage area estimates, the distribution looks the same but we have about half as many samples.

2024-10-08 17:14 UTC, jds485 commented on R/gage_locations.R
> +                           # is tens of catchments and within 10%
Thanks! the `> 100` cutoff is at least more than 1 catchment

2024-10-08 17:16 UTC, dblodgett-usgs commented on R/gage_locations.R
> +                           # is tens of catchments and within 10%
Yep! And in general, since the vast majority are under 10sqkm, it's greater than 10 catchments.

2024-10-08 17:21 UTC, merged

2024-10-08 17:21 UTC, dblodgett-usgs commented
I addressed things in a couple follow up commits and went ahead and merged. Thanks for the dialogue @jds485 !!!